### ISSUE TITLE
Help with container who has multiple tags/names

### ISSUE THREAD

**Issue by anup92k** [timdaman/check_docker#71]
Hello,

While using `check_docker` to check if the running images are the same version as those in the registry (with option `--version`), I've got this error with InfluxDB :

```
UNKNOWN: "influxdb" has multiple tags/names. Unsure which one to use to check the version. 
```

Is there a way you can explain how can I make this work correctly with InfluxDB ?

Here is the relevent part of my `docker-compose.yml` :

```yaml
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
[...]
```

Thank you.

BTW : Thanks for this cool plugin ! 👍
